--changeset karl:ddl:createTable:users
CREATE TABLE users(
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(39) NOT NULL UNIQUE
);
--rollback DROP TABLE "users";

--changeset karl:ddl:createTable:urgency_descriptors
CREATE TABLE urgency_descriptors(
	urgency_descriptor_id INT PRIMARY KEY NOT NULL,
	urgency_descriptor_name VARCHAR(30) NOT NULL UNIQUE
);
--rollback DROP TABLE "urgency_descriptors";

--changeset karl:ddl:createTable:repo_owners
CREATE TABLE repo_owners(
	repo_owner_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repo_owner_name VARCHAR(1000) NOT NULL UNIQUE
);
--rollback DROP TABLE "repo_owners";

--changeset karl:ddl:createTable:repos
CREATE TABLE repos(
	repo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repo_owner_id INT NOT NULL,
	repo_name VARCHAR(1000) NOT NULL,
	UNIQUE(repo_owner_id, repo_name)
);
--rollback DROP TABLE "repos";

--changeset karl:ddl:createTable:blames
CREATE TABLE blames(
	blame_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	blamer_id INT NOT NULL,
	blamed_id INT NOT NULL,
	urgency_descriptor_id INT NOT NULL,
	repo_id INT NOT NULL,
	blame_path VARCHAR(4096) NOT NULL,
	blame_line INT NOT NULL,
	blame_message VARCHAR(256) NOT NULL,
	blame_viewed BOOLEAN NOT NULL DEFAULT false,
	blame_complete BOOLEAN NOT NULL DEFAULT false,
	blame_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--rollback DROP TABLE "blames";