--changeset karl:ddl:createTable:Users
CREATE TABLE Users(
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(39)
);

ALTER TABLE Users
ALTER COLUMN user_name SET NOT NULL,
ADD CONSTRAINT userName_unique UNIQUE (user_name);
--rollback DROP TABLE "Users";

--changeset karl:ddl:createTable:UrgencyDescriptors
CREATE TABLE UrgencyDescriptors(
	urgency_descriptor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	urgency_descriptor_name VARCHAR(30)
);

ALTER TABLE UrgencyDescriptors
ALTER COLUMN urgency_descriptor_name SET NOT NULL;
--rollback DROP TABLE "UrgencyDescriptors";

--changeset karl:ddl:createTable:RepoOwners
CREATE TABLE RepoOwners(
	repo_owner_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repo_owner_name VARCHAR(1000)
);

ALTER TABLE RepoOwners
ALTER COLUMN repo_owner_name SET NOT NULL,
ADD CONSTRAINT repo_owner_name_unique UNIQUE (repo_owner_name);
--rollback DROP TABLE "RepoOwners";

--changeset karl:ddl:createTable:Repos
CREATE TABLE Repos(
	repo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repo_owner_id INT,
	repo_name VARCHAR(1000)
);

ALTER TABLE Repos
ALTER COLUMN repo_name SET NOT NULL;
--rollback DROP TABLE "Repos";

--changeset karl:ddl:createTable:Blames
CREATE TABLE Blames(
	blame_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	blamer_id INT,
	blamed_id INT,
	urgency_descriptor_id INT,
	repo_id INT,
	blame_path VARCHAR(4096),
	blame_line INT,
	blame_message VARCHAR(256),
	blame_accepted BOOLEAN,
	blame_complete BOOLEAN,
	blame_timestamp TIMESTAMP
);

ALTER TABLE Blames
ALTER COLUMN blame_path SET NOT NULL;

ALTER TABLE Blames
ALTER COLUMN blame_accepted SET DEFAULT false;

ALTER TABLE Blames
ALTER COLUMN blame_timestamp SET NOT NULL,
ALTER COLUMN blame_timestamp SET DEFAULT CURRENT_TIMESTAMP;
--rollback DROP TABLE "Blames";