CREATE TABLE Users(
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(39)
);

ALTER TABLE Users
ALTER COLUMN user_name SET NOT NULL,
ADD CONSTRAINT userName_unique UNIQUE (user_name);

CREATE TABLE UrgencyDescriptors(
	urgency_descriptor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	urgency_descriptor_name VARCHAR(30)
);

ALTER TABLE UrgencyDescriptors
ALTER COLUMN urgency_descriptor_name SET NOT NULL;

CREATE TABLE RepoOwners(
	repo_owner_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repo_owner_name VARCHAR(1000)
);

ALTER TABLE RepoOwners
ALTER COLUMN repo_owner_name SET NOT NULL,
ADD CONSTRAINT repo_owner_name_unique UNIQUE (repo_owner_name);


CREATE TABLE Repos(
	repo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repo_owner_id INT,
	repo_name VARCHAR(1000)
);
ALTER TABLE Repos
ALTER COLUMN repo_name SET NOT NULL;

ALTER TABLE Repos
ADD CONSTRAINT fk_repo_owner
FOREIGN KEY (repo_owner_id) REFERENCES RepoOwners(repo_owner_id);


CREATE TABLE Blames(
	blame_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	blamer_id INT,
	blamed_id INT,
	urgency_descriptor_id INT,
	repo_id INT,
	blame_path VARCHAR(4096),
	blame_line INT,
	blame_message VARCHAR(256),
	blame_accepted BOOLEAN,
	blame_complete BOOLEAN,
	blame_timestamp TIMESTAMP
);

ALTER TABLE Blames
ALTER COLUMN blame_path SET NOT NULL;

ALTER TABLE Blames
ALTER COLUMN blame_accepted SET DEFAULT false;

ALTER TABLE Blames
ALTER COLUMN blame_timestamp SET NOT NULL,
ALTER COLUMN blame_timestamp SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Blames
ADD CONSTRAINT fk_blamer
FOREIGN KEY (blamer_id) REFERENCES Users(user_id),
ADD CONSTRAINT fk_urgency_descriptor
FOREIGN KEY (urgency_descriptor_id) REFERENCES UrgencyDescriptors(urgency_descriptor_id),
ADD CONSTRAINT fk_repo
FOREIGN KEY (repo_id) REFERENCES Repos(repo_id),
ADD CONSTRAINT fk_blamed
FOREIGN KEY (blamed_id) REFERENCES Users(user_id);


